/**
 * Harman media model — every homepage image has one job.
 *
 * Audit (SECTION → ASSET → WHY):
 * Arrive  → heroVineyard        — property landscape hero
 * Place   → placeMapPath + placeAerial — intro map + scroll zoom
 * Land    → season* / farm* + mosaic tiles
 * Family  → familyStudio
 * Craft   → craftGrapes / craftCellar / craftGlass
 * Wine    → Ecwid bottles via seed (not here)
 * Table   → eatFire + pizza + foodWine
 * Gather  → cellarInterior / pergolaView / picnicLawn (distinct)
 * Region  → regionMorning / placeAerial / gatherPergola / regionEvening + region* place plates
 * Return  → returnDusk (sunsetClose aliases same plate)
 * Awards  → recognitionTexture + seed awards
 */

export type FocalPoint = `${number}% ${number}%`;

export type MediaAspect =
  | "cinematic"
  | "landscape"
  | "portrait"
  | "square"
  | "editorial";

export type MediaAsset = {
  id: string;
  src: string;
  alt: string;
  role: string;
  section: string;
  aspect: MediaAspect;
  /** Desktop object-position */
  focalPoint: FocalPoint;
  /** Mobile object-position (portrait crop) */
  focalPointMobile?: FocalPoint;
};

export const media = {
  heroVineyard: {
    id: "hero-vineyard",
    src: "/images/harman/dji_fly_20240124_153604_0002_1706413557790_photo-1-scaled.jpg",
    alt: "Aerial view of Harman Wines vineyard and cellar door at Wattle Bank",
    role: "hero",
    section: "arrive",
    aspect: "cinematic",
    focalPoint: "50% 42%",
    focalPointMobile: "48% 55%",
  },
  placeAerial: {
    id: "place-aerial",
    src: "/images/harman/dji_fly_20240124_180554_0009_1706413548051_photo-1-scaled.jpg",
    alt: "Golden-hour aerial over South Gippsland farmland toward Harman Wines",
    role: "scroll-zoom",
    section: "place",
    aspect: "cinematic",
    focalPoint: "52% 38%",
    focalPointMobile: "45% 50%",
  },
  placeMapPath: {
    id: "place-map-path",
    src: "/images/harman/generated/place-map-path.jpg",
    alt: "Path through the vineyard toward the cellar door",
    role: "place-intro",
    section: "place",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  landVines: {
    id: "land-vines",
    src: "/images/harman/cropped-vines-1.jpg",
    alt: "Autumn vine rows at Harman Wines",
    role: "winter-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  landPortrait: {
    id: "land-portrait",
    src: "/images/harman/cropped-vines-1.jpg",
    alt: "Vine rows across the Harman Wines estate",
    role: "spring-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
    focalPointMobile: "50% 40%",
  },
  seasonSummer: {
    id: "season-summer",
    src: "/images/harman/generated/season-summer.jpg",
    alt: "Summer light across the vineyard rows",
    role: "season-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  seasonAutumn: {
    id: "season-autumn",
    src: "/images/harman/cropped-vines-1.jpg",
    alt: "Autumn harvest colour in the vines",
    role: "season-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  seasonWinter: {
    id: "season-winter",
    src: "/images/harman/generated/season-winter.jpg",
    alt: "Winter pruning light over the vineyard",
    role: "season-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  seasonSpring: {
    id: "season-spring",
    src: "/images/harman/generated/season-spring.jpg",
    alt: "Spring growth beginning in the rows",
    role: "season-plate",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  farmChickens: {
    id: "farm-chickens",
    src: "/images/harman/cropped-O7I6351.jpg",
    alt: "Free-roaming chicken on the farm",
    role: "farm-mosaic",
    section: "land",
    aspect: "square",
    focalPoint: "40% 45%",
  },
  farmBanjo: {
    id: "farm-banjo",
    src: "/images/harman/generated/farm-banjo.jpg",
    alt: "Banjo the farm dog",
    role: "farm-mosaic",
    section: "land",
    aspect: "square",
    focalPoint: "50% 40%",
  },
  farmAlpacas: {
    id: "farm-alpacas",
    src: "/images/harman/generated/farm-alpacas.jpg",
    alt: "Alpacas grazing at Harman Wines",
    role: "farm-mosaic",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  farmGardenHands: {
    id: "farm-garden-hands",
    src: "/images/harman/IMG_1732-1-scaled.jpg",
    alt: "Kitchen garden and picnic lawn at Harman Wines",
    role: "farm-mosaic",
    section: "land",
    aspect: "portrait",
    focalPoint: "50% 40%",
  },
  mosaicVines: {
    id: "mosaic-vines",
    src: "/images/harman/cropped-vines-1.jpg",
    alt: "Vine canopy detail",
    role: "farm-mosaic",
    section: "land",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  mosaicGarden: {
    id: "mosaic-garden",
    src: "/images/harman/IMG_1732-1-scaled.jpg",
    alt: "Garden and picnic ground at Harman Wines",
    role: "farm-mosaic",
    section: "land",
    aspect: "portrait",
    focalPoint: "50% 40%",
  },
  mosaicDetail: {
    id: "mosaic-detail",
    src: "/images/harman/grapes.jpg",
    alt: "Estate grapes",
    role: "farm-mosaic",
    section: "land",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  familyStudio: {
    id: "family-studio",
    src: "/images/harman/cropped-Brown_D_Harman_Wines_0025-scaled-1.jpg",
    alt: "David and Nicole Harman at Harman Wines",
    role: "portrait",
    section: "family",
    aspect: "portrait",
    focalPoint: "50% 28%",
    focalPointMobile: "50% 25%",
  },
  familyTogether: {
    id: "family-together",
    src: "/images/harman/O7I6337.jpg",
    alt: "The Harman family among the vines",
    role: "family-plate",
    section: "family",
    aspect: "landscape",
    focalPoint: "45% 40%",
  },
  aboutVineyard: {
    id: "about-vineyard",
    src: "/images/harman/DJI_0007.jpg",
    alt: "Aerial view of the Harman Wines vineyard at Wattle Bank",
    role: "vineyard-hero",
    section: "land",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  awardVtaGold: {
    id: "award-vta-gold",
    src: "/images/harman/cropped-vta2025-gold-winner-reversed.jpg",
    alt: "Victorian Tourism Awards Gold Winner",
    role: "award-badge",
    section: "recognition",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  awardAtaSilver: {
    id: "award-ata-silver",
    src: "/images/harman/cropped-QTA-2025-Silver.-Tourism-Wineries-1_small.jpeg",
    alt: "Australian Tourism Awards Silver Winner",
    role: "award-badge",
    section: "recognition",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  awardGba: {
    id: "award-gba",
    src: "/images/harman/cropped-cropped-cropped-GBA-2023-Award.png",
    alt: "Gippsland Business Awards Winner",
    role: "award-badge",
    section: "recognition",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  awardPeoplesChoice: {
    id: "award-peoples-choice",
    src: "/images/harman/cropped-Peoples-Choice-Award.png",
    alt: "Bass Coast People’s Choice Award",
    role: "award-badge",
    section: "recognition",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  craftGrapes: {
    id: "craft-grapes",
    src: "/images/harman/grapes-2.jpg",
    alt: "Hand-harvested grapes",
    role: "vine",
    section: "craft",
    aspect: "portrait",
    focalPoint: "50% 45%",
  },
  craftCellar: {
    id: "craft-cellar",
    src: "/images/harman/BCS_B_AWARDS_HARMANS-WINES_010-2.jpg",
    alt: "David Harman sampling wine from barrel in the cellar",
    role: "cellar",
    section: "craft",
    aspect: "portrait",
    focalPoint: "48% 35%",
    focalPointMobile: "50% 30%",
  },
  craftGlass: {
    id: "craft-glass",
    src: "/images/harman/cropped-cropped-Brown_D_Harman_Wines_0140-2-scaled-2.jpg",
    alt: "Harman Wines tasting paddle and bottles",
    role: "glass",
    section: "craft",
    aspect: "landscape",
    focalPoint: "48% 45%",
  },
  winePaddles: {
    id: "wine-paddles",
    src: "/images/harman/9-Image-Wine-Paddles-scaled.jpeg",
    alt: "Wine tasting paddles at Harman Wines",
    role: "wine-intro",
    section: "wine",
    aspect: "editorial",
    focalPoint: "50% 50%",
  },
  tablePizza: {
    id: "table-pizza",
    src: "/images/harman/Brown_D_Harman_Wines_0364-1-scaled.jpg",
    alt: "Wood-fired pizza at Harman Wines",
    role: "food-detail",
    section: "table",
    aspect: "landscape",
    focalPoint: "45% 40%",
    focalPointMobile: "40% 35%",
  },
  tableSharedPlate: {
    id: "table-shared-plate",
    src: "/images/harman/Brown_D_Harman_Wines_0285-scaled.jpg",
    alt: "Shared plate of grilled halloumi, beetroot and rocket",
    role: "food-detail",
    section: "table",
    aspect: "landscape",
    focalPoint: "50% 45%",
    focalPointMobile: "48% 40%",
  },
  tableFoodWine: {
    id: "table-food-wine",
    src: "/images/harman/Food-and-Wine-1.png",
    alt: "Food and wine at the cellar door",
    role: "food-hero",
    section: "table",
    aspect: "landscape",
    focalPoint: "45% 48%",
    focalPointMobile: "40% 50%",
  },
  eatFire: {
    id: "eat-fire",
    src: "/images/harman/cropped-IMG_2190-scaled-1.jpg",
    alt: "Wood fire and pizza oven at the cellar door",
    role: "food-fire",
    section: "table",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  gatherInside: {
    id: "gather-inside",
    src: "/images/harman/cropped-IMG_2190-scaled-1.jpg",
    alt: "Wood-fired oven at the Harman Wines cellar door",
    role: "environment",
    section: "gather",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  gatherPergola: {
    id: "gather-pergola",
    src: "/images/harman/IMG_4700-scaled.jpg",
    alt: "Gathering under the pergola with vineyard views",
    role: "environment",
    section: "gather",
    aspect: "portrait",
    focalPoint: "50% 55%",
  },
  gatherPicnic: {
    id: "gather-picnic",
    src: "/images/harman/IMG_1732-1-scaled.jpg",
    alt: "Picnic tables beside the garden",
    role: "environment",
    section: "gather",
    aspect: "portrait",
    focalPoint: "50% 45%",
  },
  regionCoast: {
    id: "region-coast",
    src: "/images/harman/region/inverloch-coast.webp",
    alt: "Inverloch surf beach on the Bass Coast",
    role: "region-plate",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 40%",
  },
  regionMorning: {
    id: "region-morning",
    src: "/images/harman/region/bunurong-drive.webp",
    alt: "Morning along the Bunurong Coastal Drive",
    role: "region-day",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  regionEvening: {
    id: "region-evening",
    src: "/images/harman/cropped-sunset-1-e1547421800738-1.jpg",
    alt: "Evening light over South Gippsland",
    role: "region-day",
    section: "region",
    aspect: "landscape",
    focalPoint: "40% 50%",
  },
  recognitionTexture: {
    id: "recognition-texture",
    src: "/images/harman/generated/recognition-texture.jpg",
    alt: "Subtle paper texture",
    role: "texture",
    section: "recognition",
    aspect: "editorial",
    focalPoint: "50% 50%",
  },
  returnDusk: {
    id: "return-dusk",
    src: "/images/harman/cropped-sunset-1-e1547421800738-1.jpg",
    alt: "Dusk light over the vineyard at Harman Wines",
    role: "closing-heroic",
    section: "return",
    aspect: "cinematic",
    focalPoint: "35% 48%",
    focalPointMobile: "40% 55%",
  },
  sunsetClose: {
    id: "sunset-close",
    src: "/images/harman/cropped-sunset-1-e1547421800738-1.jpg",
    alt: "Dusk light over the vineyard at Harman Wines",
    role: "closing-heroic",
    section: "return",
    aspect: "cinematic",
    focalPoint: "35% 48%",
    focalPointMobile: "40% 55%",
  },
  logoWhite: {
    id: "logo-white",
    src: "/images/harman/Harman-Wines-white-01-e1547431145664.png",
    alt: "Harman Wines",
    role: "logo",
    section: "brand",
    aspect: "editorial",
    focalPoint: "50% 50%",
  },
  logoDark: {
    id: "logo-dark",
    src: "/images/harman/Harman-Wines-dark-transparent.png",
    alt: "Harman Wines",
    role: "logo",
    section: "brand",
    aspect: "editorial",
    focalPoint: "50% 50%",
  },
  awardsNight: {
    id: "awards-night",
    src: "/images/harman/BCS_B_AWARDS_HARMANS-WINES_009-1_2718f0c5fd9b09205b0f772d8c614acd.jpg",
    alt: "Harman Wines at the Bass Coast awards",
    role: "awards",
    section: "recognition",
    aspect: "landscape",
    focalPoint: "50% 40%",
  },
  sustainabilitySolar: {
    id: "sustainability-solar",
    src: "/images/harman/solar-power.jpg",
    alt: "Solar power at Harman Wines",
    role: "sustainability",
    section: "craft",
    aspect: "landscape",
    focalPoint: "50% 40%",
  },
  eventsMusic: {
    id: "events-music",
    src: "/images/harman/Music2-scaled.jpeg",
    alt: "Live music at Harman Wines",
    role: "gathering",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 40%",
  },
  eventMusicDuoIndoor: {
    id: "event-music-duo-indoor",
    src: "/images/harman/events/music-duo-indoor.jpg",
    alt: "Duo performing live music at the Harman Wines cellar door",
    role: "events-gallery",
    section: "events",
    aspect: "portrait",
    focalPoint: "50% 35%",
  },
  eventMusicDuoTent: {
    id: "event-music-duo-tent",
    src: "/images/harman/events/music-duo-tent.jpg",
    alt: "Musician performing under the tent with vineyard views",
    role: "events-gallery",
    section: "events",
    aspect: "portrait",
    focalPoint: "48% 30%",
  },
  eventMusicDuoCheck: {
    id: "event-music-duo-check",
    src: "/images/harman/events/music-duo-check.jpg",
    alt: "Guitar and vocals at a Sunday live music session",
    role: "events-gallery",
    section: "events",
    aspect: "portrait",
    focalPoint: "50% 40%",
  },
  eventMusicBand: {
    id: "event-music-band",
    src: "/images/harman/events/music-band.jpg",
    alt: "Band performing live at Harman Wines",
    role: "events-gallery",
    section: "events",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  regionHeroLeaf: {
    id: "region-hero-leaf",
    src: "/images/harman/region/hero-leaf.jpg",
    alt: "Ladybird on a vine leaf at Harman Wines",
    role: "region-hero",
    section: "region",
    aspect: "cinematic",
    focalPoint: "55% 45%",
  },
  regionInverlochCoast: {
    id: "region-inverloch-coast",
    src: "/images/harman/region/inverloch-coast.webp",
    alt: "Inverloch surf beach on the Bass Coast",
    role: "region-place",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 50%",
  },
  regionBunurong: {
    id: "region-bunurong",
    src: "/images/harman/region/bunurong-drive.webp",
    alt: "Bunurong Coastal Drive along Bass Coast",
    role: "region-hero",
    section: "region",
    aspect: "cinematic",
    focalPoint: "50% 45%",
    focalPointMobile: "50% 50%",
  },
  regionWilsonsProm: {
    id: "region-wilsons-prom",
    src: "/images/harman/region/wilsons-prom.jpg",
    alt: "Lookout over Wilsons Promontory National Park",
    role: "region-place",
    section: "region",
    aspect: "landscape",
    focalPoint: "42% 48%",
  },
  regionWineGippsland: {
    id: "region-wine-gippsland",
    src: "/images/harman/region/wine-gippsland.webp",
    alt: "Wine Gippsland",
    role: "region-logo",
    section: "region",
    aspect: "square",
    focalPoint: "50% 50%",
  },
  regionInverlochStay: {
    id: "region-inverloch-stay",
    src: "/images/harman/region/inverloch-stay.webp",
    alt: "Inverloch Accommodation",
    role: "region-logo",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 50%",
  },
  regionInverlochGlamping: {
    id: "region-inverloch-glamping",
    src: "/images/harman/region/inverloch-glamping.jpg",
    alt: "Glamping near Inverloch",
    role: "region-place",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 45%",
  },
  regionMindBodySoul: {
    id: "region-mind-body-soul",
    src: "/images/harman/region/mind-body-soul.png",
    alt: "Mind Body Soul Day Spa Inverloch",
    role: "region-logo",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 50%",
  },
  regionDestinationGippsland: {
    id: "region-destination-gippsland",
    src: "/images/harman/region/destination-gippsland.png",
    alt: "Destination Gippsland",
    role: "region-logo",
    section: "region",
    aspect: "landscape",
    focalPoint: "50% 50%",
  },
} as const satisfies Record<string, MediaAsset>;

export type MediaKey = keyof typeof media;

/** @deprecated Prefer `media` — thin aliases for older call sites */
export const images = {
  logoWhite: media.logoWhite.src,
  logoDark: media.logoDark.src,
  aerialDay: media.heroVineyard.src,
  aerialGolden: media.placeAerial.src,
  vineyardPortrait: media.landPortrait.src,
  cellarMoment: media.craftCellar.src,
  vinesClose: media.landVines.src,
  grapes: media.mosaicDetail.src,
  winePaddles: media.winePaddles.src,
  foodWine: media.tableFoodWine.src,
  gathering: media.gatherPergola.src,
  picnicOrGarden: media.gatherPicnic.src,
  awardsNight: media.awardsNight.src,
  portrait: media.familyStudio.src,
  awardVta2025: "/images/harman/cropped-vta2025-gold-winner-reversed.jpg",
  awardAta2025: "/images/harman/cropped-QTA-2025-Silver.-Tourism-Wineries-1_small.jpeg",
  awardGba2023: "/images/harman/cropped-cropped-cropped-GBA-2023-Award.png",
  wines: {
    blancDeBlanc18: "/images/harman/wines/blanc-de-blanc-18.jpg",
    rose2024: "/images/harman/wines/rose-2024.jpg",
    pinotNoir2023: "/images/harman/wines/612-estate-pinot-noir-2023.jpg",
    sauvBlanc2024: "/images/harman/wines/sauvignon-blanc-2024.jpg",
    syrah2022: "/images/harman/wines/gippsland-syrah-2022.jpg",
  },
} as const;
